theme = "tokyonight_storm"

[editor]
line-number="relative"
bufferline="multiple"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]

[editor.cursor-shape]
insert = "bar"

[editor.lsp]
enable=true
display-messages=true
